/** @format */

module.exports = [
	{ label: "Adrar", value: "Adrar" },
	{ label: "Chlef", value: "Chlef" },
	{ label: "Laghouat", value: "Laghouat" },
	{ label: "Oum El Bouaghi", value: "Oum El Bouaghi" },
	{ label: "Batna", value: "Batna" },
	{ label: "Béjaïa", value: "Béjaïa" },
	{ label: "Biskra", value: "Biskra" },
	{ label: "Béchar", value: "Béchar" },
	{ label: "Blida", value: "Blida" },
	{ label: "Bouira", value: "Bouira" },
	{ label: "Tamanrasset", value: "Tamanrasset" },
	{ label: "Tébessa", value: "Tébessa" },
	{ label: "Tlemcen", value: "Tlemcen" },
	{ label: "Tiaret", value: "Tiaret" },
	{ label: "Tizi Ouzou", value: "Tizi Ouzou" },
	{ label: "Alger", value: "Alger" },
	{ label: "Djelfa", value: "Djelfa" },
	{ label: "Jijel", value: "Jijel" },
	{ label: "Sétif", value: "Sétif" },
	{ label: "Saïda", value: "Saïda" },
	{ label: "Skikda", value: "Skikda" },
	{ label: "Sidi Bel Abbès", value: "Sidi Bel Abbès" },
	{ label: "Annaba", value: "Annaba" },
	{ label: "Guelma", value: "Guelma" },
	{ label: "Constantine", value: "Constantine" },
	{ label: "Médéa", value: "Médéa" },
	{ label: "Mostaganem", value: "Mostaganem" },
	{ label: "M'Sila", value: "M'Sila" },
	{ label: "Mascara", value: "Mascara" },
	{ label: "Ouargla", value: "Ouargla" },
	{ label: "Oran", value: "Oran" },
	{ label: "El Bayadh", value: "El Bayadh" },
	{ label: "Illizi", value: "Illizi" },
	{ label: "Bordj Bou Arreridj", value: "Bordj Bou Arreridj" },
	{ label: "Boumerdès", value: "Boumerdès" },
	{ label: "El Tarf", value: "El Tarf" },
	{ label: "Tindouf", value: "Tindouf" },
	{ label: "Tissemsilt", value: "Tissemsilt" },
	{ label: "El Oued", value: "El Oued" },
	{ label: "Khenchela", value: "Khenchela" },
	{ label: "Souk Ahras", value: "Souk Ahras" },
	{ label: "Tipaza", value: "Tipaza" },
	{ label: "Mila", value: "Mila" },
	{ label: "Aïn Defla", value: "Aïn Defla" },
	{ label: "Naâma", value: "Naâma" },
	{ label: "Aïn Témouchent", value: "Aïn Témouchent" },
	{ label: "Ghardaïa", value: "Ghardaïa" },
	{ label: "Relizane", value: "Relizane" },
	{ label: "Timimoun", value: "Timimoun" },
	{ label: "Bordj Badji Mokhtar", value: "Bordj Badji Mokhtar" },
	{ label: "Ouled Djellal", value: "Ouled Djellal" },
	{ label: "Béni Abbès", value: "Béni Abbès" },
	{ label: "In Salah", value: "In Salah" },
	{ label: "In Guezzam", value: "In Guezzam" },
	{ label: "Touggourt", value: "Touggourt" },
	{ label: "Djanet", value: "Djanet" },
	{ label: "El Meghaier", value: "El Meghaier" },
	{ label: "El Menia", value: "El Menia" },
];
